name: Blog
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3.3.1
      id: go
      with:
        go-version: 1.15
    - uses: actions/checkout@v2
    - name: Test Build
      run: |
        cd blog/blog && go get ./... && make install
