name: Scavenge
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.1.0
        id: go
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
      - name: Test Build
        run: |
          cd scavenge/scavenge && go get ./... && make install
