name: Voter
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.15
    - uses: actions/checkout@v3.1.0
    - name: Test Build
      run: |
        cd voter/voter && go get ./... && make install
